diff --git a/lib/Makefile b/lib/Makefile
index 7147512..4aee8bd 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -23,3 +23,8 @@ ename.c.inc :
 
 clean :
 	${RM} *.o ename.c.inc ${TLPI_LIB}
+
+HDRS := $(wildcard *.h)
+install:
+	cp ${HDRS} ${TLPI_INSTALL}/include
+	cp ${TLPI_LIB} ${TLPI_INSTALL}/lib
